//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameAnswer
    {
        public System.Guid AnswerId { get; set; }
        public System.Guid GameQuestionId { get; set; }
        public System.Guid PlayerId { get; set; }
        public string Answer { get; set; }
        public bool AnswerCorrect { get; set; }
    
        public virtual GamePlayer GamePlayer { get; set; }
        public virtual GameQuestion GameQuestion { get; set; }
    }
}
