//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlayer
    {
        public System.Guid Id { get; set; }
        public System.Guid GameRoomId { get; set; }
        public System.Guid PlayerId { get; set; }
        public string PlayerName { get; set; }
    
        public virtual GameRoom GameRoom { get; set; }
    }
}
