//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TriviaService
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameSetting
    {
        public int PlayerCount { get; set; }
        public short QuestionCount { get; set; }
    }
}
